---
title: "Simulation Study"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
library(ggpubr)
library(here)
setwd(here())
```

# Association between a component forecaster's point prediction and importance 

```{r}
dat <- readRDS("../Data/simulation_f3pts.rds")
p1 <- dat %>% 
    ggplot(aes(x=f3_pred, y =Importance_score, group=Model)) +
    geom_line(aes(linetype=Model)) +
    scale_linetype_manual(values=c("dashed","twodash", "solid"),
                          labels = c("forecaster 1","forecaster 2","forecaster 3")) +
    labs(x="b (prediction of forecaster 3)", y="Average  Importance", 
         title = bquote(bold("(a) Average Importance based on -SPE"))) +
    theme(legend.position = "bottom") + 
    theme(axis.text=element_text(size=12),
          axis.title=element_text(size=14),
          strip.text = element_text(size = 12),
          legend.title = element_text(size=14),
          legend.text = element_text(size=14))
```


## Association between a component forecaster's bias and importance

```{r plot_imp_bias}
simdat <- readRDS("../Data/simulation_f3bias.rds")

p2 <- simdat %>% rename(Model = model) %>% 
        dplyr::select(Model, f3_bias, importance, dispersion) %>%
        dplyr::group_by(f3_bias, Model) %>%
        dplyr::summarise(sharpness=mean(dispersion), 
                           avg_imp=mean(importance), 
                           "5% qt"=quantile(importance, probs = 0.05), 
                           #"50% qt"=quantile(importance, probs = 0.50),
                           "95% qt"=quantile(importance, probs = 0.95), 
                         .groups = 'drop') %>% 
        ggplot(aes(x=f3_bias, y =avg_imp, group=Model)) +
        geom_line(aes(linetype=Model)) +
        scale_linetype_manual(values=c("dashed","twodash", "solid"),
                          labels = c("forecaster 1","forecaster 2","forecaster 3")) +
        labs(x="b (bias of forecaster 3)", y="Average  Importance", 
         title = bquote(bold("(b) Average Importance based on -WIS"))) +
        theme(legend.position = "bottom") + 
        theme(axis.text=element_text(size=12),
              axis.title=element_text(size=14),
              strip.text = element_text(size = 12),
              legend.title = element_text(size=14),
              legend.text = element_text(size=14))
```


```{r}
p <- ggarrange(p1, p2, ncol = 2, common.legend = TRUE, legend = "bottom")
pdf(file="../Plot/simulation-settingA.pdf",
    width = 10,
    height = 5)
p
dev.off()
```


## Association between component forecaster dispersion and importance

```{r plot_imp_dispersion}
simdat <- readRDS("../Data/simulation_f3sharp.rds")

p3 <- simdat %>% rename(Model = model) %>%  
        dplyr::select(Model, f3_sharpness, importance, dispersion) %>%
        dplyr::group_by(f3_sharpness, Model) %>%
        dplyr::summarise(sharpness=mean(dispersion), 
                           avg_imp=mean(importance), 
                           "5% qt"=quantile(importance, probs = 0.05), 
                           #"50% qt"=quantile(importance, probs = 0.50),
                           "95% qt"=quantile(importance, probs = 0.95), 
                         .groups = 'drop') %>% 
        ggplot(aes(x=f3_sharpness, y =avg_imp, group=Model)) +
        geom_line(aes(linetype=Model)) +
        scale_linetype_manual(values=c("dashed","twodash", "solid"),
                              labels = c("forecaster 1","forecaster 2","forecaster 3")) +
        labs(x="s (standard deviation of forecaster 3)",
             #title="Importance of three forecasters by different dispersion of forecaster 3", 
             y="Average  Importance") + 
        theme(axis.text=element_text(size=12),
              axis.title=element_text(size=14),
              strip.text = element_text(size = 12),
              legend.title = element_text(size=14),
              legend.text = element_text(size=14))
```

```{r}
pdf(file="../Plot/simulation-settingB.pdf",
    width = 10,
    height = 5)
p3
dev.off()
```