---
title: "Supplement"
output:
  pdf_document: default
  html_document: default
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressPackageStartupMessages(library(tidyverse))
library(dplyr)
library(magrittr)
library(lubridate)
library(pander)
library(ggpubr) # ggarrange
library(ggbump)
library(GGally) 
suppressPackageStartupMessages(library(GGally)) # for 'ggpairs'
library(here)
setwd(here())
```

```{r}
source("../Rcode/relative_wis.R") 
```

# Drop NAs

Drop all NAs

```{r NAdrop-table}
df_all_scores_extended <- readRDS("../Data/df_all_scores_extended.rds")
df_all_scores_extended_NAdrop <- df_all_scores_extended %>% drop_na()

# compute relative wis compared to the "COVIDhub-baseline" model
relWIS <- relative_wis(df_all_scores_extended_NAdrop)

compare_NAdrop <- df_all_scores_extended_NAdrop %>% 
        group_by(model) %>% 
        summarise(meanWIS = mean(wis),
                  meanRank = mean(std_rank),
                  meanImpScore_shapley_eq = mean(ImpScore_shapley_eq),
                  meanImpScore_shapley_wt = mean(ImpScore_shapley_wt),
                  meanImpScore_lomo_eq = mean(ImpScore_lomo_eq),
                  meanImpScore_lomo_wt = mean(ImpScore_lomo_wt)) %>% 
        ungroup() %>% 
        left_join(relWIS, by="model") %>%
        mutate(model = reorder(factor(model), meanWIS)) %>%
        arrange(meanWIS) %>% 
        relocate(relWIS, .after = meanWIS) %>% 
        mutate_if(is.numeric, ~round(., 2))

# saveRDS(compare_NAdrop, "../Data/compare_NAdrop.rds")
compare_NAdrop <- readRDS("../Data/compare_NAdrop.rds")

compare_NAdrop %>% 
        rename(WIS=meanWIS, 
               Rank=meanRank, 
               Shapley.eq = meanImpScore_shapley_eq,
               Shapley.wt = meanImpScore_shapley_wt,
               LOMO.eq = meanImpScore_lomo_eq,
               LOMO.wt = meanImpScore_lomo_wt) %>% 
        pander(caption = "Summary of mean WIS, rank, importance scores with 
               untrained and trained ensembles by dropping NA values.",
               justify = "right", 
               split.table = Inf)
```

```{r NAdrop-plot}
g1 <- compare_NAdrop %>% ggplot() + 
        geom_point(aes(model, meanWIS), color = "deeppink") 
g2 <- compare_NAdrop %>% ggplot() + 
        geom_point(aes(model, meanRank), color = "green2") +
        scale_x_discrete(guide = guide_axis(angle = 30)) +
        labs(x=NULL)
g3 <- compare_NAdrop %>% ggplot() + 
        geom_point(aes(model, meanImpScore_shapley_eq), color = "red") +
        labs(y="Shapley.eq") 
g4 <- compare_NAdrop %>% ggplot() + 
        geom_point(aes(model, meanImpScore_lomo_eq), color = "blue") +
        labs(y="LOMO.eq") +
        scale_x_discrete(guide = guide_axis(angle = 30))

g5 <- compare_NAdrop %>% ggplot() + 
        geom_point(aes(model, meanImpScore_shapley_wt), color = "red2") +
        labs(y="Shapley.wt") 
g6 <- compare_NAdrop %>% ggplot() + 
        geom_point(aes(model, meanImpScore_lomo_wt), color = "blue2") +
        labs(y="LOMO.wt") +
        scale_x_discrete(guide = guide_axis(angle = 30))


remove_x <- theme(
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank(),
  axis.title.x = element_blank()
)

plots_wis_rk <- ggarrange(g1 + remove_x, g2,ncol = 1, heights = c(0.65, 1))  
annotate_figure(plots_wis_rk, top = text_grob("mean WIS and mean Rank", 
               face = "bold", size = 14))

plots_untrained <- ggarrange(g3 + remove_x, g4,ncol = 1, heights = c(0.65, 1)) 
annotate_figure(plots_untrained, top = text_grob("mean Importance Score (untrained) ", 
               face = "bold", size = 14))

plots_trained <- ggarrange(g5 + remove_x, g6,ncol = 1, heights = c(0.65, 1)) 
annotate_figure(plots_trained, top = text_grob("mean Importance Score (trained) ", 
               face = "bold", size = 14))
```

```{r pairs-plot-NAdrop, message=FALSE}
d_NAdrop <- compare_NAdrop %>% 
        mutate(neg_WIS=-meanWIS) %>% 
        relocate(neg_WIS, .after=model) %>% 
        select(model, neg_WIS, meanImpScore_shapley_eq, meanImpScore_lomo_eq)

colnames <- c(paste0("-WIS"),  
              "Phi^{lasomo}", 
              "Phi^{lomo}")

p.pairs.NAdrop <- ggpairs(
        d_NAdrop %>% select(-1),
        columnLabels = colnames,
        labeller = "label_parsed"
        ) + 
        theme(strip.text = element_text(size = 14),
              panel.spacing = unit(0.65, "lines"))

p.pairs.NAdrop 

pdf(file="../Plot/corr-NAdrop.pdf",
    width = 10,
    height = 5)
p.pairs.NAdrop
dev.off()
```



```{r plot-rank-changes-NAdrop}
df_rank <- compare_NAdrop %>%
        mutate(WIS_rank = rank(meanWIS), 
               lasomo_eq_rank = rank(-meanImpScore_shapley_eq),
               lasomo_wt_rank = rank(-meanImpScore_shapley_wt),
               lomo_eq_rank = rank(-meanImpScore_lomo_eq),
               lomo_wt_rank = rank(-meanImpScore_lomo_wt)) %>% 
        select(model, WIS_rank, lasomo_eq_rank, lasomo_wt_rank, lomo_eq_rank, lomo_wt_rank) 

# Plot: WIS vs. Phi[eq]^{lasomo}
rank_lasomo_eq <- df_rank %>% 
        mutate(line_type = case_when(
                                WIS_rank < lasomo_eq_rank ~ "twodash",
                                WIS_rank > lasomo_eq_rank ~ "dotted",
                                TRUE ~ "solid"
                                )
               ) %>%
        select(model, WIS_rank, lasomo_eq_rank, line_type) %>%
        pivot_longer(cols = c(WIS_rank, lasomo_eq_rank), 
                     names_to = "Metric", 
                     values_to = "Rank") %>% 
        ggplot(aes(x = Metric, y = Rank, group = model, linetype = line_type)) +
        geom_bump(linewidth=2) +
        geom_point(size=0, alpha = 0.1) +
        scale_x_discrete(limits = rev, labels = c("-WIS", expression(Phi^{lasomo})),
                         expand = c(0.45, 0.45)) +
        scale_y_continuous(trans="reverse", breaks = 1:10) +
        labs(title = bquote(bold("(a) -WIS vs. " * Phi^{lasomo})),
             x = "") +
        # Add labels for each line
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "lasomo_eq_rank"),  # Place label at the last point
                  hjust = "left",  
                  nudge_x = 0.03,
                  size = 6 )   +
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "WIS_rank"),  # Place label at the starting point
                  hjust = "right", 
                  nudge_x = -0.03,
                  size = 6)   +
        theme_bw() +
        theme(legend.position = "none",
              axis.title = element_text(size = 22),
              axis.text.x = element_text(size = 22),
              axis.text.y = element_text(size = 18),
              plot.title = element_text(size=23)) 
 
# Plot: WIS vs. Phi[wt]^{lasomo}
rank_lasomo_wt <- df_rank %>% 
        mutate(line_type = case_when(
                                WIS_rank < lasomo_wt_rank ~ "twodash",
                                WIS_rank > lasomo_wt_rank ~ "dotted",
                                TRUE ~ "solid"
                                )
               ) %>%
        select(model, WIS_rank, lasomo_wt_rank, line_type) %>%
        pivot_longer(cols = c(WIS_rank, lasomo_wt_rank), 
                     names_to = "Metric", 
                     values_to = "Rank") %>% 
        ggplot(aes(x = Metric, y = Rank, group = model, linetype = line_type)) +
        geom_bump(linewidth=2) +
        geom_point(size=0, alpha = 0.1) +
        scale_x_discrete(limits = rev, labels = c("-WIS", expression(Phi[wt]^{lasomo})),
                         expand = c(0.45, 0.45)) +
        scale_y_continuous(trans="reverse", breaks = 1:10) +
        labs(title = bquote(bold("(b) -WIS vs. " * Phi[wt]^{lasomo})),
             x = "", y="") +
        # Add labels for each line
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "lasomo_wt_rank"),  # Place label at the last point
                  hjust = "left",  
                  nudge_x = 0.03,
                  size = 6 )   +
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "WIS_rank"),  # Place label at the starting point
                  hjust = "right", 
                  nudge_x = -0.03,
                  size = 6)   +
        theme_bw() +
        theme(legend.position = "none",
              axis.title = element_text(size = 22),
              axis.text.x = element_text(size = 22),
              axis.text.y = element_text(size = 18),
              plot.title = element_text(size=23))       

# Plot: WIS vs. Phi[eq]^{lomo}
rank_lomo_eq <- df_rank %>% 
        mutate(line_type = case_when(
                                WIS_rank < lomo_eq_rank ~ "twodash",
                                WIS_rank > lomo_eq_rank ~ "dotted",
                                TRUE ~ "solid"
                                )
               ) %>%
        select(model, WIS_rank, lomo_eq_rank, line_type) %>%
        pivot_longer(cols = c(WIS_rank, lomo_eq_rank), 
                     names_to = "Metric", 
                     values_to = "Rank") %>% 
        ggplot(aes(x = Metric, y = Rank, group = model, linetype = line_type)) +
        geom_bump(linewidth=2) +
        geom_point(size=0, alpha = 0.1) +
        scale_x_discrete(limits = rev, labels = c("-WIS", expression(Phi^{lomo})),
                         expand = c(0.45, 0.45)) +
        scale_y_continuous(trans="reverse", breaks = 1:10) +
        labs(title = bquote(bold("(c) -WIS vs. " * Phi^{lomo})), y=" ") +
        # Add labels for each line
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "lomo_eq_rank"),  # Place label at the last point
                  hjust = "left",  
                  nudge_x = 0.03,
                  size = 6 )   +
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "WIS_rank"),  # Place label at the starting point
                  hjust = "right", 
                  nudge_x = -0.03,
                  size = 6)   +
        theme_bw() +
        theme(legend.position = "none",
              axis.title = element_text(size = 22),
              axis.text.x = element_text(size = 22),
              axis.text.y = element_text(size = 18),
              plot.title = element_text(size=23)) 

# Plot: WIS vs. Phi[wt]^{lomo}
rank_lomo_wt <- df_rank %>% 
        mutate(line_type = case_when(
                                WIS_rank < lomo_wt_rank ~ "twodash",
                                WIS_rank > lomo_wt_rank ~ "dotted",
                                TRUE ~ "solid"
                                )
               ) %>%
        select(model, WIS_rank, lomo_wt_rank, line_type) %>%
        pivot_longer(cols = c(WIS_rank, lomo_wt_rank), 
                     names_to = "Metric", 
                     values_to = "Rank") %>% 
        ggplot(aes(x = Metric, y = Rank, group = model, linetype = line_type)) +
        geom_bump(linewidth=2) +
        geom_point(size=0, alpha = 0.1) +
        scale_x_discrete(limits = rev, labels = c("-WIS", expression(Phi[wt]^{lomo})),
                         expand = c(0.45, 0.45)) +
        scale_y_continuous(trans="reverse", breaks = 1:10) +
        labs(title = bquote(bold("(d) -WIS vs. " * Phi[wt]^{lomo})), y=" ") +
        # Add labels for each line
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "lomo_wt_rank"),  # Place label at the last point
                  hjust = "left",  
                  nudge_x = 0.03,
                  size = 6 )   +
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "WIS_rank"),  # Place label at the starting point
                  hjust = "right", 
                  nudge_x = -0.03,
                  size = 6)   +
        theme_bw() +
        theme(legend.position = "none",
              axis.title = element_text(size = 22),
              axis.text.x = element_text(size = 22),
              axis.text.y = element_text(size = 18),
              plot.title = element_text(size=23)) 

pdf(file="../Plot/rank-changes-lasomo-eq-NAdrop.pdf",
    width = 10,
    height = 8)
rank_lasomo_eq
dev.off()

pdf(file="../Plot/rank-changes-lasomo-wt-NAdrop.pdf",
    width = 10,
    height = 8)
rank_lasomo_wt
dev.off()

pdf(file="../Plot/rank-changes-lomo-eq-NAdrop.pdf",
    width = 10,
    height = 8)
rank_lomo_eq
dev.off()

pdf(file="../Plot/rank-changes-lomo-wt-NAdrop.pdf",
    width = 10,
    height = 8)
rank_lomo_wt
dev.off()
```


# Replace NAs with the average score

For each model, location (l), time (t), horizon (h), replace NAs by the average score; by mean WIS over all non-NA models for WIS, by 0.5 for rank, by mean importance over all non-NA models.

```{r NAavg-table}
df_all_scores_extended_NAavg <- readRDS("../Data/df_all_scores_extended_NAavg.rds")

# compute relative wis compared to the "COVIDhub-baseline" model
relWIS <- relative_wis(df_all_scores_extended_NAavg)

compare_NAavg <- df_all_scores_extended_NAavg %>% 
        group_by(model) %>% 
        summarise(meanWIS = mean(wis),
                  meanRank = mean(std_rank),
                  meanImpScore_shapley_eq = mean(ImpScore_shapley_eq),
                  meanImpScore_shapley_wt = mean(ImpScore_shapley_wt),
                  meanImpScore_lomo_eq = mean(ImpScore_lomo_eq),
                  meanImpScore_lomo_wt = mean(ImpScore_lomo_wt)) %>% 
        ungroup() %>% 
        left_join(relWIS, by="model") %>% 
        mutate(model = reorder(factor(model), meanWIS)) %>%
        arrange(meanWIS) %>% 
        relocate(relWIS, .after = meanWIS) %>% 
        mutate_if(is.numeric, ~round(., 2))

# saveRDS(compare_NAavg, "../Data/compare_NAavg.rds")
compare_NAavg <- readRDS("../Data/compare_NAavg.rds")

compare_NAavg %>% 
        rename(WIS=meanWIS, 
               Rank=meanRank, 
               Shapley.eq = meanImpScore_shapley_eq,
               Shapley.wt = meanImpScore_shapley_wt,
               LOMO.eq = meanImpScore_lomo_eq,
               LOMO.wt = meanImpScore_lomo_wt) %>% 
        pander(caption = "Summary of mean WIS, rank, importance scores 
               with untrained and trained ensembles 
               by replaceing NA values with the mean of the corresponding metric.",
               justify = "right", 
               split.table = Inf)

```


```{r NAavg-plot}
g1 <- compare_NAavg %>% ggplot() + 
        geom_point(aes(model, meanWIS), color = "deeppink") 
g2 <- compare_NAavg %>% ggplot() + 
        geom_point(aes(model, meanRank), color = "green2") +
        scale_x_discrete(guide = guide_axis(angle = 30)) +
        labs(x=NULL)
g3 <- compare_NAavg %>% ggplot() + 
        geom_point(aes(model, meanImpScore_shapley_eq), color = "red") +
        labs(y="Shapley.eq") 
g4 <- compare_NAavg %>% ggplot() + 
        geom_point(aes(model, meanImpScore_lomo_eq), color = "blue") +
        labs(y="LOMO.eq") +
        scale_x_discrete(guide = guide_axis(angle = 30))

g5 <- compare_NAavg %>% ggplot() + 
        geom_point(aes(model, meanImpScore_shapley_wt), color = "red2") +
        labs(y="Shapley.wt") 
g6 <- compare_NAavg %>% ggplot() + 
        geom_point(aes(model, meanImpScore_lomo_wt), color = "blue2") +
        labs(y="LOMO.wt") +
        scale_x_discrete(guide = guide_axis(angle = 30))


remove_x <- theme(
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank(),
  axis.title.x = element_blank()
)

plots_wis_rk <- ggarrange(g1 + remove_x, g2,ncol = 1, heights = c(0.65, 1))  
annotate_figure(plots_wis_rk, top = text_grob("mean WIS and mean Rank", 
               face = "bold", size = 14))

plots_untrained <- ggarrange(g3 + remove_x, g4,ncol = 1, heights = c(0.65, 1)) 
annotate_figure(plots_untrained, top = text_grob("mean Importance Score (untrained) ", 
               face = "bold", size = 14))

plots_trained <- ggarrange(g5 + remove_x, g6,ncol = 1, heights = c(0.65, 1)) 
annotate_figure(plots_trained, top = text_grob("mean Importance Score (trained) ", 
               face = "bold", size = 14))
```


```{r pairs-plot-NAavg, message=FALSE}
d_NAavg <- compare_NAavg %>% 
        mutate(neg_WIS=-meanWIS) %>% 
        relocate(neg_WIS, .after=model) %>% 
        select(model, neg_WIS, meanImpScore_shapley_eq, meanImpScore_lomo_eq)

colnames <- c(paste0("-WIS"),  
              "Phi^{lasomo}", 
              "Phi^{lomo}")

p.pairs.NAavg <- ggpairs(
        d_NAavg %>% select(-1),
        columnLabels = colnames,
        labeller = "label_parsed"
        ) + 
        theme(strip.text = element_text(size = 14),
              panel.spacing = unit(0.65, "lines"))

p.pairs.NAavg 

pdf(file="../Plot/corr-NAavg.pdf",
    width = 10,
    height = 5)
p.pairs.NAavg
dev.off()
```


```{r plot-rank-changes-NAavg}
df_rank <- compare_NAavg %>%
        mutate(WIS_rank = rank(meanWIS), 
               lasomo_eq_rank = rank(-meanImpScore_shapley_eq),
               lasomo_wt_rank = rank(-meanImpScore_shapley_wt),
               lomo_eq_rank = rank(-meanImpScore_lomo_eq),
               lomo_wt_rank = rank(-meanImpScore_lomo_wt)) %>% 
        select(model, WIS_rank, lasomo_eq_rank, lasomo_wt_rank, lomo_eq_rank, lomo_wt_rank) 

# Plot: WIS vs. Phi[eq]^{lasomo}
rank_lasomo_eq <- df_rank %>% 
        mutate(line_type = case_when(
                                WIS_rank < lasomo_eq_rank ~ "twodash",
                                WIS_rank > lasomo_eq_rank ~ "dotted",
                                TRUE ~ "solid"
                                )
               ) %>%
        select(model, WIS_rank, lasomo_eq_rank, line_type) %>%
        pivot_longer(cols = c(WIS_rank, lasomo_eq_rank), 
                     names_to = "Metric", 
                     values_to = "Rank") %>% 
        ggplot(aes(x = Metric, y = Rank, group = model, linetype = line_type)) +
        geom_bump(linewidth=2) +
        geom_point(size=0, alpha = 0.1) +
        scale_x_discrete(limits = rev, labels = c("-WIS", expression(Phi^{lasomo})),
                         expand = c(0.45, 0.45)) +
        scale_y_continuous(trans="reverse", breaks = 1:10) +
        labs(title = bquote(bold("(a) -WIS vs. " * Phi^{lasomo})),
             x = "") +
        # Add labels for each line
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "lasomo_eq_rank"),  # Place label at the last point
                  hjust = "left",  
                  nudge_x = 0.03,
                  size = 6 )   +
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "WIS_rank"),  # Place label at the starting point
                  hjust = "right", 
                  nudge_x = -0.03,
                  size = 6)   +
        theme_bw() +
        theme(legend.position = "none",
              axis.title = element_text(size = 22),
              axis.text.x = element_text(size = 22),
              axis.text.y = element_text(size = 18),
              plot.title = element_text(size=23)) 
 
# Plot: WIS vs. Phi[wt]^{lasomo}
rank_lasomo_wt <- df_rank %>% 
        mutate(line_type = case_when(
                                WIS_rank < lasomo_wt_rank ~ "twodash",
                                WIS_rank > lasomo_wt_rank ~ "dotted",
                                TRUE ~ "solid"
                                )
               ) %>%
        select(model, WIS_rank, lasomo_wt_rank, line_type) %>%
        pivot_longer(cols = c(WIS_rank, lasomo_wt_rank), 
                     names_to = "Metric", 
                     values_to = "Rank") %>% 
        ggplot(aes(x = Metric, y = Rank, group = model, linetype = line_type)) +
        geom_bump(linewidth=2) +
        geom_point(size=0, alpha = 0.1) +
        scale_x_discrete(limits = rev, labels = c("-WIS", expression(Phi[wt]^{lasomo})),
                         expand = c(0.45, 0.45)) +
        scale_y_continuous(trans="reverse", breaks = 1:10) +
        labs(title = bquote(bold("(b) -WIS vs. " * Phi[wt]^{lasomo})),
             x = "", y="") +
        # Add labels for each line
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "lasomo_wt_rank"),  # Place label at the last point
                  hjust = "left",  
                  nudge_x = 0.03,
                  size = 6 )   +
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "WIS_rank"),  # Place label at the starting point
                  hjust = "right", 
                  nudge_x = -0.03,
                  size = 6)   +
        theme_bw() +
        theme(legend.position = "none",
              axis.title = element_text(size = 22),
              axis.text.x = element_text(size = 22),
              axis.text.y = element_text(size = 18),
              plot.title = element_text(size=23))       

# Plot: WIS vs. Phi[eq]^{lomo}
rank_lomo_eq <- df_rank %>% 
        mutate(line_type = case_when(
                                WIS_rank < lomo_eq_rank ~ "twodash",
                                WIS_rank > lomo_eq_rank ~ "dotted",
                                TRUE ~ "solid"
                                )
               ) %>%
        select(model, WIS_rank, lomo_eq_rank, line_type) %>%
        pivot_longer(cols = c(WIS_rank, lomo_eq_rank), 
                     names_to = "Metric", 
                     values_to = "Rank") %>% 
        ggplot(aes(x = Metric, y = Rank, group = model, linetype = line_type)) +
        geom_bump(linewidth=2) +
        geom_point(size=0, alpha = 0.1) +
        scale_x_discrete(limits = rev, labels = c("-WIS", expression(Phi^{lomo})),
                         expand = c(0.45, 0.45)) +
        scale_y_continuous(trans="reverse", breaks = 1:10) +
        labs(title = bquote(bold("(c) -WIS vs. " * Phi^{lomo})), y=" ") +
        # Add labels for each line
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "lomo_eq_rank"),  # Place label at the last point
                  hjust = "left",  
                  nudge_x = 0.03,
                  size = 6 )   +
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "WIS_rank"),  # Place label at the starting point
                  hjust = "right", 
                  nudge_x = -0.03,
                  size = 6)   +
        theme_bw() +
        theme(legend.position = "none",
              axis.title = element_text(size = 22),
              axis.text.x = element_text(size = 22),
              axis.text.y = element_text(size = 18),
              plot.title = element_text(size=23)) 

# Plot: WIS vs. Phi[wt]^{lomo}
rank_lomo_wt <- df_rank %>% 
        mutate(line_type = case_when(
                                WIS_rank < lomo_wt_rank ~ "twodash",
                                WIS_rank > lomo_wt_rank ~ "dotted",
                                TRUE ~ "solid"
                                )
               ) %>%
        select(model, WIS_rank, lomo_wt_rank, line_type) %>%
        pivot_longer(cols = c(WIS_rank, lomo_wt_rank), 
                     names_to = "Metric", 
                     values_to = "Rank") %>% 
        ggplot(aes(x = Metric, y = Rank, group = model, linetype = line_type)) +
        geom_bump(linewidth=2) +
        geom_point(size=0, alpha = 0.1) +
        scale_x_discrete(limits = rev, labels = c("-WIS", expression(Phi[wt]^{lomo})),
                         expand = c(0.45, 0.45)) +
        scale_y_continuous(trans="reverse", breaks = 1:10) +
        labs(title = bquote(bold("(d) -WIS vs. " * Phi[wt]^{lomo})), y=" ") +
        # Add labels for each line
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "lomo_wt_rank"),  # Place label at the last point
                  hjust = "left",  
                  nudge_x = 0.03,
                  size = 6 )   +
        geom_text(aes(label = model), 
                  data = . %>% filter(Metric == "WIS_rank"),  # Place label at the starting point
                  hjust = "right", 
                  nudge_x = -0.03,
                  size = 6)   +
        theme_bw() +
        theme(legend.position = "none",
              axis.title = element_text(size = 22),
              axis.text.x = element_text(size = 22),
              axis.text.y = element_text(size = 18),
              plot.title = element_text(size=23)) 

pdf(file="../Plot/rank-changes-lasomo-eq-NAavg.pdf",
    width = 10,
    height = 8)
rank_lasomo_eq
dev.off()

pdf(file="../Plot/rank-changes-lasomo-wt-NAavg.pdf",
    width = 10,
    height = 8)
rank_lasomo_wt
dev.off()

pdf(file="../Plot/rank-changes-lomo-eq-NAavg.pdf",
    width = 10,
    height = 8)
rank_lomo_eq
dev.off()

pdf(file="../Plot/rank-changes-lomo-wt-NAavg.pdf",
    width = 10,
    height = 8)
rank_lomo_wt
dev.off()
```

